/*
 * app/api/review/analyst/route.ts
 * -----------------------------------------------------------------------
 * Stage 2 of the review pipeline: run the Analyst agent over the record
 * text and retrieved snippets produced by stage 1
 * (app/api/review/retrieve/route.ts).
 *
 * This is a genuine, separate network request -- not a continuation of
 * the same request that did retrieval -- specifically so its loading
 * duration in the UI reflects the real latency of one Claude API call,
 * not an artificial pause. The client (app/page.tsx) calls this only
 * after stage 1 has returned.
 * -----------------------------------------------------------------------
 */

import { NextResponse } from "next/server";
import { runAnalyst } from "@/lib/agents/analyst";
import type { AnalystOutput, ReferenceSnippet } from "@/types/review";

export const dynamic = "force-dynamic";

interface AnalystRequestBody {
  recordText?: unknown;
  retrievedSnippets?: unknown;
}

/** Minimal shape validation for the incoming JSON body. We don't re-run
 *  the full ReferenceSnippet validation field-by-field here -- the
 *  snippets were generated by our own /retrieve endpoint moments
 *  earlier, not arbitrary external input -- we just confirm the basic
 *  shape is sane before passing it on to the Analyst agent. */
function parseRequestBody(body: AnalystRequestBody): {
  recordText: string;
  retrievedSnippets: ReferenceSnippet[];
} {
  if (typeof body.recordText !== "string" || body.recordText.length === 0) {
    throw new Error('Expected a non-empty "recordText" string field.');
  }
  if (!Array.isArray(body.retrievedSnippets)) {
    throw new Error('Expected a "retrievedSnippets" array field.');
  }
  return {
    recordText: body.recordText,
    retrievedSnippets: body.retrievedSnippets as ReferenceSnippet[],
  };
}

export async function POST(request: Request): Promise<NextResponse> {
  let recordText: string;
  let retrievedSnippets: ReferenceSnippet[];

  try {
    const body = (await request.json()) as AnalystRequestBody;
    ({ recordText, retrievedSnippets } = parseRequestBody(body));
  } catch (error) {
    const message = error instanceof Error ? error.message : "Invalid request body.";
    return NextResponse.json({ error: message }, { status: 400 });
  }

  try {
    const analyst: AnalystOutput = await runAnalyst(recordText, retrievedSnippets);
    return NextResponse.json({ analyst }, { status: 200 });
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "The Analyst agent failed unexpectedly.";
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
